### PR TITLE
silence no-return warning

### PR DESCRIPTION
**Pull request by federkamm**

### CODE REVIEW

**Comment by federkamm** [comment]
"enum"s are not considered "complete", therefore the 'switch' doesn't know it handled every case.  I think "enum class"es would be considered "complete" and the warning might not be issued.

**Comment by Glavnokoman** [comment]
Which compiler is that and what exactly is the warning?
(I can't compile it locally any more, needs to be updated for the newer vulkan-headers probably)
All possible values of the enum are handled here (correct me if I am wrong). 
So if we silence the false warning by dummy return, there will be no warning if the enum is extended but the new value is not handled here.

**Comment by federkamm** [comment]
The complete waring is 

../../src/device.cpp: In function 'std::vector<vuh::QueueSpec> vuh::{anonymous}::to_specs(const vuh::PhysicalDevice&, vuh::QueueSpec::Preset)':
../../src/device.cpp:141:1: warning: control reaches end of non-void function [-Wreturn-type]
  141 | }
      | ^

on MinGW64 (Windows 10): gcc.exe (Rev3, Built by MSYS2 project) 10.1.0

GCC seems to be not as good as clang in detecting "complete" enumeration switches.

The "no return value" and the "unhandled enum cases in switch" should be independent of each other.  The enum should spot an unhandled case wether there is code following it or not.  I would expect the "no return value" would at most conflict with a "code can't be reached" warning.

As alterative, for gcc (and clang) instead of the "return" statement the compiler hint:

  __builtin_unreachable();

could be used to silence the warning (probably even the better idea since it shouldn't emit the code for the last return).  However, this dosen't work for eg. MSVC (I think).

**Comment by Glavnokoman** [comment]
> The enum should spot an unhandled case wether there is code following it or not. I would expect the "no return value" would at most conflict with a "code can't be reached" warning.

Makes sense.

**Pull request merged**
